- .jshintrc
- README.md
- default_index.html
- index.js
- package.json
- spec/HtmlWebpackPluginSpec.js
- spec/fixtures/legacy.html
- spec/fixtures/legacy_default_index.html
- spec/fixtures/test.html
This pull request deprecates the usage of  `{%=o.htmlWebpackPlugin.assets%}` and creates a new representation called `{%=o.htmlWebpackPlugin.files%}`.
Maybe you can come up with a better name than `files`.
I had to rename  `assets` to `files` to support existing (< 1.1.0) templates.
Example structure of the  `{%=o.htmlWebpackPlugin.files%}` object:
```js
{
"manifest" : "manifest.appcache",
"css" : [
"app.css"
],
"js" : [
"commons.js",
"index_bundle.js"
],
"chunks" : {
"commons" : {
"entry" : "commons.js",
"css" : [
]
},
"app" : {
"entry" : "index_bundle.js",
"css" : [
"app.css"
]
}
}
}
```
It works well together with the https://github.com/lettertwo/appcache-webpack-plugin and https://github.com/webpack/extract-text-webpack-plugin
Added support for cache busting by using the webpack …
> Support for .css and .manifest files and cache busting

- index.js
Fixes error reporting so that instead of:
Error in undefined
We get:
Error in HtmlWebPackPlugin: htmlWebpackPlugin.assets is deprecated - please use htmlWebpackPlugin.files instead
> Fixes error reporting

- index.js
As far as I know, getting the file size within the template is not possible.
I added a way to get it like this: ``` {%=o.htmlWebpackPlugin.files.chunks.main.size %}```
The file size is important in my case in order to have a progress loader via http request so I can do something like that:
```
function ajax(url, onProgress, callback, data, x) {
try {
x = new(this.XMLHttpRequest || ActiveXObject)('MSXML2.XMLHTTP.3.0');
x.open(data ? 'POST' : 'GET', url, 1);
x.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
x.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
x.onreadystatechange = function() {
x.readyState > 3 && callback && callback(x.responseText, x);
};
x.addEventListener("progress", onProgress, false);
x.send(data)
} catch (e) {
window.console && …
```
> Adding the file size to the chunk object

- package.json
Lodash being on 3.9.3 is killing 'npm shrinkwrap' in one of my current projects. On a not-so-personal note, who wouldn't want to have a green dependencies badge on her project page, right? ;)
Made sure tests still pass.
> Bump project dependencies

- README.md
- index.js
All `html-minifier` options are `false` by default, so passing just true does nothing to the output
> Passing true to minify does nothing

- index.js
- spec/HtmlWebpackPluginSpec.js
There are two case my colleague ran into:
1. when we are using relative publicPath - it generates ```<script src='..\../main.js'>``` instead of safe web ```<script src='../../main.js'>```. In pull request I wrapped **publicPath** with **url.resolve**.
2. when in path to template we are using forward slashes on windows build breaks and index.html is not generated. In pull request i wrapped it with **path.normalize**.
> On Windows relative path doesn't work properly

- index.js
- spec/HtmlWebpackPluginSpec.js
Previously the first 3 characters were stripped from the beginning of the source; it assumed these characters are `var`. When using the webpack.BannerPlugin, the source starts with the given comment and after that `var result` is used. This is fixed now and I've added a test for this.
This may not be the most clean solution, but it works.
> Add support for webpack.BannerPlugin

- index.js
I've incorporated 396cdedf8a554465d00797bb4d279b085e2e05d8 into the `feature/loaders` branch, which should fix the failing tests for old Node.js versions.
> Fix publicPath for feature/loaders

- index.js
- spec/HtmlWebpackPluginSpec.js
Webpack gives the possibility to use the build [hash] in
output.publicPath option:
https://webpack.github.io/docs/long-term-caching.html
However HtmlWebpackPlugin is reading directly the raw option, preventing the
user to use this option when using it.
> FIX missing [hash] interpolation in publicPath

- index.js
It used `this` instead of `self` and there was not errors because they there caught and not forwarded back to promise (forgotten `return` before `Promise.reject()`).
Btw, why need to `try..catch` if you are already in `Promise`, shouldn't it be auto-rejected on error?
> Fix minify option

- index.js
- loader.js
Without this, it will throw `ERROR in Template execution failed: ReferenceError: _ is not defined` when use `<%- something %>` in template.
The template functions referenced `_.escape`, and it lost the reference when transform it to string.
> Support lodash template's HTML "escape" delimiter (<%- %>)

- lib/loader.js
This PR removes changes included with `commit b3913d04001f031342794c71acfc4a1bae4e01b3`.
Why?
- `commit b3913d` makes `lodash` a dependency for user's app. Not every user will use `lodash`. Those who don't use lodash will run into error.
- When I upgrade `html-webpack-plugin@2.1` to `html-webpack-plugin@2.6`, my build script crashed because of reason above. The `commit b3913d` leads to incompatibility.
- I think `escape` is not that important and we have other approach.
More details:
- <https://github.com/ampedandwired/html-webpack-plugin/pull/160> 
- <https://github.com/ampedandwired/html-webpack-plugin/issues/172>
> Remove lodash as dependency, fix #172

- lib/compiler.js
fix for https://github.com/webpack/webpack/issues/1890
yes, I know, this should be done automatically by webpack when creating a child compilation...
I'll add it in the next major version...
> Child compilation must use a separate cache object

- index.js
- spec/HtmlWebpackPluginSpec.js
- spec/fixtures/webpackconfig.html
Add chunk hash to `assets.chunks` so can use it in template.
For some version control requirements, chunk hash may be more useful than compilation hash.
For example, if there are two chunks in page, but only one of them is changed, use chunk hash is more cache-friendly.
> Add chunk hash to `assets.chunks`

- lib/compiler.js
For some errors, no other parameters to the function are even given,
only the error object in `err`.
> Properly throw an error in compiler even when childCompilation is missing

- .travis.yml
Io.js was never made LTS, so no real reason to test on it. And 4.2.x (now 4.3.1) is the LTS release since the merge
https://github.com/nodejs/LTS
> Test on alle LTS releases of Node

- index.js
- migration.md
- spec/HtmlWebpackPluginSpec.js
- spec/fixtures/templateParam.js
> Add additional compilation property to the templateParam object

- README.md
- index.js
- spec/HtmlWebpackPluginSpec.js
Some apps require xhtml tags to be generated (like here https://github.com/webpack/extract-text-webpack-plugin/issues/160)
> Add xhtml option to make link tags self-closing

- index.js
- spec/HtmlWebpackPluginSpec.js
Currently if my webpack config has: `publicPath: "/dist/[hash]/"` then my output html file will have:  `<script src="/dist/[hash]/commons_11e1b2480d26bdc6c179.js">`
WIth this fix [hash] gets replaced with the actual hash value.
> build public path with correct hash value

- README.md
A gotcha if two plugins use the same event: the callback must be passed the htmlPluginData (and any err). This PR corrects the example code in the README.md
> Corrected README.md Events example code

- index.js
webpack-dev-server@2.0.0-beta seems to be emitting hot update bundles separately from the full bundle. This makes HtmlWebpackPlugin mistake it for the real bundle, and generates a HTML file that looks like this:
```html
<script src="0.8f9c33574d86dd9eab0d.hot-update.js"></scriptt>
```
This commit uses quite a hack to check if the emitted bundle is a hot-update bundle, and skip emitting `index.html` file.
> Don’t emit the html for hot-update compilation.

- package.json
This makes `peerDependences` match what other Webpack 2 beta compatible loaders and plugins I'm using are doing, as `*` doesn't seem to match pre-release versions.
Making this change locally fixed a `peerDependency` error I was getting installing Webpack 2 beta and dependencies with npm2, which makes `npm install` with that version of npm.
> Update peerDependencies to support use with Webpack 2 beta and npm2

- index.js
- spec/BasicSpec.js
[hash] replacement works for pretty much all asset types but if the publicPath includes the build hash it does not get replaced and the final html output for the favicon and still contains the [hash] placeholder. this change replaces the [hash] variable in the publicPath for the favicon.
> replace [hash] in publicPath of favicon

- index.js
- spec/BasicSpec.js
Hi @jantimon,
I came up with this simple solution to satisfy both needs.
This approach:
- keep backwards compatibility
- offer a new api to deal with `html-webpack-plugin-(before|after)-html-processing`
> Made before and after "html-processing" events use callback value

- index.js
- spec/BasicSpec.js
@jantimon I excluded the `html-webpack-plugin-after-emit` event from returned result check and fixed tests.
Take a look :)
> Resolve 'html-webpack-plugin-after-emit' deprecated warnings

- README.md
Fixed some typos and changed `html` to `HTML` in text.
> Typos and edits in README.md

- index.js
More details in this issue: #541
> Fix template path resolving regexp to support loader query parameters

- index.js
Add support for JS template with:
```js
export default (templateParams) => ...
```
> Fix template compilation for es6 modules

- .travis.yml
`PrettyErrors`'s  dependecy `RenderKid` needs TTY columns to word-wrap lines to console.
> Fix travis-ci: set tty size

- README.md
After a fresh `yarn install`, all tests were failing. I had to do `yarn link && yarn link html-webpack-plugin` to get them to work, since some files are required as e.g. `html-webpack-plugin/lib/loader.js`.
> Document `yarn link` before running tests

- lib/chunksorter.js
`chunk.parents` are insurance of `Chunk` instead of string `id`(s):
This PR supports both webpack1 and webpack2.
Some example from webpack:
https://github.com/webpack/webpack/blob/b07dc3da275402d7128c06d762e840f25b31c54c/lib/optimize/CommonsChunkPlugin.js#L165
https://github.com/webpack/webpack/blob/028c51301733836abbedc88be7483af2623f5943/lib/Chunk.js#L141
> fix(chunksorter): webpack2 compatible

- index.js
- spec/BasicSpec.js
Minor bug fix to ensure `chunks` param passed to `alter-assets` event - will also allow implementation of  [style-ext-html-webpack-plugin](https://github.com/numical/style-ext-html-webpack-plugin) to be simplified.
> chunks passed to alter-assets event

- lib/loader.js
this.resourcePath will avoid not skipping resource file with query params
> this.resourcePath will avoid not skipping resource file with query params

- docs/template-option.md
I lost half a day because I also had a file loader for .html and somehow the output got garbled. Hopefully this will help someone else.
> Make example more explicit about filename

- README.md
As discussed in issue https://github.com/jantimon/html-webpack-plugin/issues/600, [inline-chunk-manifest-html-webpack-plugin](https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin) handles the usecase of inlining webpack's chunk manifest.
This PR is to link to `inline-chunk-manifest-html-webpack-plugin`, with description for the plugin's default scenario (which can be overriden).
> Link plugin for inlining chunk manifest

- README.md
As read like this, I thought I had to import html-minifier and give the object as parameter like:
```javascript
import htmlMinifier from 'html-minifier'
new HtmlWebpackPlugin({
template: 'src/index.html',
minify: htmlMinifier,
}),
```
> docs(README): clearer explanation about minify

- README.md
In 2.6.1, 
output: {
path: 'dist',
filename: 'app.bundle.js'
}
give the below error.
The provided value "dist" is not an absolute path!
So made, path: 
output: {
path: __dirname + '/dist',
filename: 'index_bundle.js'
}
> README.md updated path property in output

- index.js
- spec/BasicSpec.js
This PR introduces a singleton cache for the compilation stats.
In large Webpack builds generating the stats takes a while and each generated html pays that cost three times. Moreover, if the build uses multiple instances of HtmlWebpackPlugin to generate more than one html file, this cost is payed for each template.
In my local case, I have ~2000 modules and 18 html templates, which normally takes around 175 seconds. With this change, the time goes down to 148 seconds, a 15% improvement.
> Uses a singleton cache to store the compilation stats

- README.md
- docs/template-option.md
Hello!
It came to my attention that the default loader was being referred to as a ejs loader, when in fact it is a loadsh loader. The syntaxes for both look almost identical, which made it harder to realize what the difference was.
I'm not super fond of the wording I came up with to modify the docs, so I'd be open to other suggestions.
Let me know if this looks good.
> Reference lodash loader by default

- README.md
Documentation didn't mention `compilation` variable available in templates, which is crucial for inlining assets in html, even though there is an example in the repo using this variable.
> docs(README): update template variables list

- README.md
I've searched for inlining solution by Ctrl+F'ing `inline`. Went for #104 and found last comment by luck. Then only found that this plugin was already mentioned in README. Spelling `in-line` is a bit strange, in my opinion. I understand that this is a smallish change, so feel free to decline changes. :v:
> Change in-line spelling

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
Based on #825 but without a new option (by now)
> Speed up build

- README.md
Per @thelarkinn's suggestion, it is necessary to order `html-webpack-plugin` first before other plugins that make use of it.
> Add a note about ordering first

- index.js
follow up to commit 0348d6b
Upgrading to Webpack 4 (possibly by switching from [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) to [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) I ended up with chunks that look like
```js
{
"id": 17,
"rendered": true,
"initial": true,
"entry": false,
"size": 1014209,
"names": [
"app"
],
"files": [
"static/css/app.ebfdfd28fd7984cf790d.css",
"static/js/app.ebfdfd28fd7984cf790d.js"
],
"hash": "ebfdfd28fd7984cf790d",
"siblings": [
// …
],
"parents": [],
"children": [
// …
]
}
```
which currently translates to the following `htmlWebpackPlugin.files`:
```js
{
"publicPath": "/gustav/",
"chunks": {
"app": {
"css": ["/gustav/static/css/app.ebfdfd28fd7984cf790d.css"]
}
},
"js": [], …
```
> fix(entries): do not ignore JS if there is also CSS

- README.md
apparently `|` in code blocks in tables need to be escaped these days…
> docs(readme): fix options table

- README.md
- index.js
- spec/BasicSpec.js
- spec/fixtures/templateParam.js
> feat: Allow to overwrite the templateParameter 

- lib/loader.js
Tries to revert a change which was done for webpack 2 to be compatible with use strict:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
> fix(loader): Allow to add new template parameters

- README.md
It's no longer allowed to omit the '-loader' suffix when using loaders. You need to specify 'handlebars-loader' instead of 'handlebars', see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
> Add -loader suffix to handlerbars

- index.js
- lib/compiler.js
This is a wip proposal to reuse a single compiler for multiple HtmlWebpackPlugin instances.
#962
#965
> feat(compiler): Use a single compiler for multiple plugin instances

- README.md
- index.js
- lib/compiler.js
- lib/hooks.js
- spec/BasicSpec.js
- spec/ExampleSpec.js
Export all hooks static and typed similar to https://github.com/webpack/webpack/pull/7672
cc @ooflorent
> feat(hooks): Provide static getHook method for access to all html-webpack-plugin hooks

- examples/default/dist/webpack-4/index.html
- examples/favicon/dist/webpack-4/favicon.html
- index.js
- typings.d.ts
Added a default viewport:
```
<meta name="viewport" content="width=device-width, initial-scale=1">
```
fix  #897, fix #978
> feat: Add default viewport meta tag for default template

- .gitignore
- index.js
- lib/compiler.js
- lib/loader.js
- package.json
- spec/basic.spec.js
- spec/caching.spec.js
- spec/example.spec.js
- tsconfig.json
Based on #967 -  try to im prove the performance by caching the entire child compilation.
This chang verifies the cache by comparing the child compilations file dependencies with the main compilation timestamps.
> feat(compiler): Use timestamps to verify cache validity

- migration.md
Minor improvement to the migration docs that highlights the fact that unescaped output has an unexpected syntax change.
> Improve migration docs in regards to changes in template syntax

- README.md
Hello!
Noticed this option was missing from docs. Let me know if there are any issues with adding it, or if you'd like the wording changed a bit. 
This plugin is extremely handy by the way! Thanks for maintaining it. 😃
> docs: add 'templateContent' option

- examples/build-examples.js
- examples/chunk-optimization/dist/webpack-4/entryA.html
- examples/chunk-optimization/dist/webpack-4/entryA.js
- examples/chunk-optimization/dist/webpack-4/entryA~entryB.js
- examples/chunk-optimization/dist/webpack-4/entryB.html
- examples/chunk-optimization/dist/webpack-4/entryB.js
- examples/chunk-optimization/dist/webpack-4/libMath.js
- examples/chunk-optimization/dist/webpack-4/libText.js
- examples/chunk-optimization/dist/webpack-4/vendors~entryA~entryB.js
- examples/chunk-optimization/entryA.js
- examples/chunk-optimization/entryB.js
- examples/chunk-optimization/lib-concat.js
- examples/chunk-optimization/lib-multiply.js
- examples/chunk-optimization/lib-sum.js
- examples/chunk-optimization/main.css
- examples/chunk-optimization/readme.md
- examples/chunk-optimization/webpack.config.js
Adds an example for #968 
```
EntryA uses 
multiply
concat
```
Therefore both cunks `libMath` and `libText` are added to entryA.html:
```
<script src="libMath.js"></script>
<script src="libText.js"></script>
<script src="vendors~entryA~entryB.js"></script>
<script src="entryA~entryB.js"></script><script src="entryA.js"></script>
```
```
EntryB uses 
multiply
```
In this case only `libMath` is added to entryB.html:
```
<script src="libMath.js"></script>
<script src="vendors~entryA~entryB.js"></script>
<script src="entryA~entryB.js"></script>
<script src="entryB.js">
```
> docs: Add an example with chunk splitting

- README.md
csp-html-webpack-plugin adds CSP meta tags to the HTML output.
> Add csp-html-webpack-plugin

- index.js
- spec/basic.spec.js
Some `webpack.config.js` configuration :
```js
export default {
entry: {
'index': './pages/index.js',
'about/index': './pages/about/index.js',
},
output: {
path: './build',
filename: '[name].js',
publicPath: process.env.PUBLIC_URL || '',
},
plugins: [
new HtmlWebpackPlugin({
filename: 'index.html',
chunks: ['index'],
}),
new HtmlWebpackPlugin({
filename: 'about/index.html',
chunks: ['about/index'],
}),
],
}
```
After the compilation is completed: 
The generated `build/index.html` looks good, but `build/about/index.html` like this:
```html
<script type="text/javascript" src="about/index.js"></script>
```
The correct path should be `../about/index.js` or `index.js`.
**So, I tried to solve the problem when publicPath was set to relative path.**
> feat: Add publicPath support relative path

- index.js
- spec/basic.spec.js
This allows to use `contenthash` which was removed in #1062 . Now when filename is provided with `contenthash` it will be internally replaced to `templatehash`
Fixes: #1033
> Allow use of contenthash along with templatehash

- docs/template-option.md
Old link goes to old docs warning then redirects to main webpack page. Found the relevant content in the new webpack docs and replaced the link.
> Update link address to loader order in Webpack docs

- .github/lock.yml
Since it creates too much email notification noise, and the reason for locking should be clear enough on its own (it's performed by a username of `lockbot` and the status of the issue/PR is set to `"resolved"`).
I decided against adding a label, since it will only end up adding noise to the labels list and issue/PR search results that adds little value other than as a workaround for inability to set a custom GitHub lock reason.
Fixes #1085.
> chore: No longer leave a comment when issues/PRs are locked

- README.md
The readme file currently states that there's a FAQ document somewhere. Searching around I went to the issues tracker and found the link to the correct location in this [issue](https://github.com/jantimon/html-webpack-plugin/issues/999).
> fix(README): adds a link to template option documentation

- lib/compiler.js
See https://github.com/jantimon/html-webpack-plugin/issues/1089
@niieani could you please take a look if this would be the required change?
> feat: drop workaround for "Uncaught TypeError: __webpack_require__(….) is not a function" to be compatible with webpack 5

- index.js
- lib/hooks.js
- lib/html-tags.js
- package.json
- typings.d.ts
This resolves #1108
* Adds `types` property to `package.json` (see [Publishing docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html))
* Revamps the `typings.d.ts` file to more accurately reflect both the internal and external API. Specifically, the `Options` interface should have every property marked optional (for external consumption) but most of those properties are assumed to be not null/undefined throughout `index.js`. I thus introduced an `InternalOptions` interface which matches this requirement.
* Moved the `Hooks` typedef into the `typings.d.ts` file vs defining it inline.
* Moved `HtmlTagObject` inside the `HtmlWebpackPlugin` namespace.
I did not fix compatibility with `noImplicitAny` in this PR. As you are shipping an annotated JS file, I believe …
> Fix TypeScript types

- index.js
- package.json
- typings.d.ts
#1132 improved the typescript definition files a lot however it also introduced some bugs which caused typechecks to fail.
This pull request uses `Partial` for `HtmlPluginOptions` to allow specifying the actual processed options in an easier way.
> fix: Repair typings

- README.md
- index.js
- spec/basic.spec.js
this will let users inject a `base` tag in a manner similar to the current implementation for `title` and `meta`. 
It also includes [docs](https://github.com/atstp/html-webpack-plugin/tree/add-base-support#base-tag) along with two new tests (`adds a base tag with attributes` and `adds a base tag short syntax`) for the introduced features.
I didn't see a contributing guide, so if you have any other questions or requests just let me know.
> introduce support for <base> (matching <title> and <meta>)

- README.md
- index.js
- spec/basic.spec.js
- spec/fixtures/src/index.ejs
BREAKING CHANGE: Use `src/index.ejs` if no template option is set.
Webpack will pick up `src/` by default that means depending on your resolving settings it will use `src/index.js`, `src/index.jsx`, `src/index.ts` ... or similar by default.
This pull request adds the same feature for the html-webpack-plugin.
I would love to know what you think in general about this pull request and if we should support:
`src/index.ejs`
`src/index.html`
or
`public/index.html`
cc @sokra @edmorley
> fix: Use src/index.ejs by default if present

- README.md
The [ExtractTextPlugin](https://github.com/webpack-contrib/extract-text-webpack-plugin#usage) docs warn:
> Since webpack v4 the extract-text-webpack-plugin should not be used for css. Use [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) instead.
This PR updates the README to reflect this change.
> README: Update mention of css plugin

- migration.md
Fix migration.md by adding `module.rules` rather than `module.loaders` and `pug-loader` rather than just `pug`.
> Fix migration.md

- lib/loader.js
Hey noticed a tiny typo in the comment.
"as aminimalistic loader" => "as a minimalistic loader"
> Fix tiny typo

- lib/loader.js
- spec/caching.spec.js
> fix: Prevent lodash from being inlined to work around a babel-loader incompatibility

- index.js
- spec/basic.spec.js
> Properly encode file names emitted as part of URLs.

- package.json
This pull requests updates lodash to address this vulnerability: https://npmjs.com/advisories/1065
commitizen also needed to be updated since its older version also depended on a vulnerable version of lodash.
> update lodash dependency for prototype polution vulnerability

- examples/custom-insertion-position/readme.md
Had "inside.ejs" instead of "index.ejs"
> Fix README typo

- lib/compiler.js
> refactor: Use getAssetPath instead of calling the hook directly

- README.md
- index.js
- spec/basic.spec.js
- typings.d.ts
This feature allows faster script loading by making use of the `defer` script loading capability of modern browsers to prevent pausing html parsing:
Usage:
```js
new HtmlWebpackPlugin({
scriptLoading: 'defer'
});
```
> feat: Add defer script loading

- package.json
- typings.d.ts
Just upgraded to 4.0.0. I had to patch the type definitions to make `tsc` happy. Seems like this got lost during the switch to `html-minifier-terser` in  c66766cdae3593091dee413b9c585359c24ef068.
> Update typedefs after switch to html-minifier-terser

- index.js
- spec/basic.spec.js
Fix for the issue https://github.com/jantimon/html-webpack-plugin/issues/1370
by default the html-minifier would turn `<demo />` into `<demo>`.
advantage: will fix problems for people using xml elements inside html (e.g. #1370)
disadvantage: if someone would add `<img .. />` it  can't be minified anymore to `<img>`.
> fix: don't remove trailing slashes from self closing tags by default

- package.json
`typings.d.ts` depends on @types/webpack, @types/tapable and @types/html-minifier-terser: https://github.com/jantimon/html-webpack-plugin/blob/v4.0.2/typings.d.ts#L1-L3
Thus they should be in dependencies instead of devDependencies like the "old" @types/html-webpack-plugin npm package: https://www.npmjs.com/package/@types/html-webpack-plugin?activeTab=dependencies
> Typings depends on @types webpack, tapable and html-minifier-terser

- examples/README.md
Now I remaking the example for supporting multi static pages.
So I delete the example link temporarily because url is broken.
> fix: delete example Landing Page 

- index.js
- spec/basic.spec.js
fix #1355
```
fo:demonstration-path/very fancy+name.js?path=/home?value=abc&value=def#zzz
^            ^    ^    ^     ^    ^  ^    ^^    ^     ^   ^     ^   ^
|            |    |    |     |    |  |    ||    |     |   |     |   |
encoded         |    |    encoded    |  |    ||    |     |   |     |   |
ignored              ignored  ignored     ignored   ignored              
```
> fix: Fix querystring encoding

- README.md
- index.js
- lib/html-tags.js
- spec/basic.spec.js
- typings.d.ts
This templateContent features has already existed before but it was wrongly typed and not well documented.
It allows inline templates:
**webpack.config.js**
```js
new HtmlWebpackPlugin({
templateContent: `
<html>
<body>
<h1>Hello World</h1>
</body>
</html>
`
})
```
The `templateContent` can also access all `templateParameters` values.  
**webpack.config.js**
```js
new HtmlWebpackPlugin({
injext: false
templateContent: ({htmlWebpackPlugin}) => `
<html>
<head>
${htmlWebpackPlugin.tags.headTags}
</head>
<body>
<h1>Hello World</h1>
${htmlWebpackPlugin.tags.bodyTags}
</body>
</html>
`
})
```
⚠️ **This approach does not allow to use weboack loaders for your template and will not update the template on changes**
> feat: Add template content

- README.md
As this was removed a while back, and now just gives `"dependency" is not a valid chunk sort mode`
> Remove `dependency` as valid `chunksSortMode`

- lib/webpack5/file-watcher-api.js
this pr fixes a bug which added dependencies multiple times
https://github.com/webpack/webpack/issues/10789
thanks @sokra
> fix: don't add dependencies twice to the webpack 5 watcher api

- examples/template-parameters/webpack.config.js
PR #1331 introduces new behavior that merges a passed object with the defaults. Fixes #1416 where the templateParameters example is out-of-date.
> Update templateParameters example to account for object merging

- index.js
Allow `console.log` (or `error`, `warn`....) inside templates.
E.g.:
```js
<% console.log("Hello World") %>
```
The output will be written by webpack (so it will be visible in the terminal not in the browser console)
> feat: Allow to use console.log inside templates

- README.md
I noticed that the the famous excludeAssets plugin is incompatible with html-webpack-plugin v4+ and has been idle for ~2 years, so I developed a drop in replacement, which is backwards compatible and allows the usage of minimatch blobs or regex patterns.
> Add skip-assets plugin to plugin list

- README.md
Doesn't seem like there's a reason it should link to the plugins section.
> Remove link from "chunksSortMode" in README

- lib/child-compiler.js
I had an error that was thrown in my webpack.config.ts that was causing childCompilation to fail. But I didn't know it was an error thrown in my webpack.config.ts because child-compiler.js didn't include the stack trace in the error message.
The stack trace I got ended at line 122 in node_modules\html-webpack-plugin\lib\child-compiler.js. So I fiddled with that to make it output the inner error stack trace and then I got the actual place of the error.
> Add stacktrace to error message from childCompilation.errors

- index.js
- lib/child-compiler.js
#1408
What I did:
- Deleted depreciation warnings in v5 (`mainTemplate.getAssetPath`, and `getPublicPath`)
- Added backward compatibility with v4
I also consider to put this `webpackMajorVersion`, as a helper somewhere - is quite repeated few times. Feedback will be needed.
> added v5 compilation support and deleted depreciation warnings

- typings.d.ts
class declaration is outside the namespace, so it needs to use it as a prefix to access its types.
> fix: broken typings.d.ts in v4.4.0

- README.md
- index.js
- typings.d.ts
- add publicPath
- align with webpack 5 "auto" public path
> feat: Add publicPath option to overrule the default path generation

- index.js
@jantimon As per mentioned in https://github.com/jantimon/html-webpack-plugin/issues/1527
> do not convert favicon to string

- README.md
Hi, I can no longer support two of the plugins listed in your README so they should be removed.
If someone chooses to fork and maintain these going forward, then they can ask for them to be restoted here.
Thanks for the platform!
Sorry I can no longer be part of it.
> remove deprecated plugins from readme

- README.md
As per listed in CHANGELOG and in https://github.com/jantimon/html-webpack-plugin/blob/74fae99c1294c01b71c8ea082fe1557cb5375322/index.js#L54, the default value for `scriptLoading` has changed to `'defer'`
> Update scriptLoading's default on README.md

- lib/html-tags.js
- spec/basic.spec.js
- typings.d.ts
This `pull request` update the _html tag parsing_ to also omit attributes that contains `null` and `undefined` value.
The motivation behind this change you can find on the [Issue #1597](https://github.com/jantimon/html-webpack-plugin/issues/1597).
> PS: not sure if this is a `feat` or ` fix` 🤷‍♂️, it depends on how you see it.
> feat: omit html tag attribute with null/undefined/false value

- typings.d.ts
The default value of the `scriptLoading` option was changed to "defer" in 35b6b87.
> hotfix: document v5.0 change to default scriptLoading

- README.md
Fixes https://github.com/jantimon/html-webpack-plugin/issues/1653
The documentation indicates that the `<scripts>` are added to the `<body>` tag by default. This is not true. They are added to the `<head>` tag by default.
This update to the documentation will avoid developer confusion by reflecting the actual behavior.
> Update README to document actual behavior

- package.json
- fix #1651 
- update "commitizen" to "^4.2.4"
- update "mini-css-extract-plugin" to "^1.6.0"
- update "standard-version" to "^9.3.0"
- update "pretty-error" to "^3.0.4"
- fix #1645 
- update "lodash" to "^4.17.21"
Side note: `npm audit` still shows for me the vulnerability: https://npmjs.com/advisories/1753 but I did not see the import `meow`.
Thoughts?
> Fix security vulnerabilities

- examples/default/dist/webpack-5/bundle.js
- examples/multi-page/dist/webpack-5/first.js
- examples/multi-page/dist/webpack-5/second.js
- lib/child-compiler.js
- lib/loader.js
- package.json
We can't use `__non_webpack_require__`, becaue it generates `import` for ESM, use old workaround to prevent analize by webpack, anyway in future we should avoid using lodash at all and provide an options to inject this for developers
> fix: compatibility with ES modules output

- index.js
- spec/basic.spec.js
- spec/fixtures/src/index.ejs
fixes https://github.com/jantimon/html-webpack-plugin/issues/1387
> fix: don't add extra meta tag if it exists

- README.md
Hi, I publish a `html-webpack-plugin` to output Django static tags, and I added it to the README.
e.g.
```django
{# before #}
<script defer src="dist/js/runtime.1198543abbf33da21374.js"></script>
{# after #}
<script defer src="{% static 'dist/js/runtime.1198543abbf33da21374.js' %}"></script>
```
> docs: added html-webpack-plugin-django to README

- spec/example.spec.js
Speed up tests by calling `done(err)` to fail a test when assertion fails, instead of waiting for timeout.
> test(examples): throw right when test fails instead of wait for timeout

- index.js
- lib/cached-child-compiler.js
- lib/child-compiler.js
- lib/chunksorter.js
- lib/hooks.js
- typings.d.ts
Here:
- simplify logic
- avoid overhead `Promise.resolve()` (not eveywhere, we need improve it more)
- reduce complexy
- types fixes
- TODO for the next major release
- avoid extra clonning and other unnecessary overhead
- and more
It is the first part of refactor, we need:
- avoid using `Promise.resolve()`/etc in favor `async`/`await`
- remove CacheChildCompiler in favor built-in webpack cache (compat with current behaviour, at the end this option will do nothing and just will be removed)
- autogeneration types from jsdocs
- readable code and simple code
> refactor: code

- index.js
fixes: https://github.com/jantimon/html-webpack-plugin/issues/1710
> fix: avoid have undefined `type` for script tags

- spec/fixtures/html-template-with-image.html
- spec/hot.spec.js
fixes https://github.com/jantimon/html-webpack-plugin/issues/1639, it is already fixed, just a test case
> test case for serve and reemitting

- README.md
Hi, this PR is mainly to solve the problem when choosing `js file` as project entry especially in a `Micro Frontend Project`
And the source code is inspired by `html-webpack-plugin`
Usage: 
```js
import JSEntryWebpackPlugin from 'js-entry-webpack-plugin'
module.exports = {
entry: 'index.js',
output: {
path: __dirname + '/dist',
},
plugins: [new JSEntryWebpackPlugin()],
}
```
Thanks for checking, if possible, add it on the awesome list which can be convenient for others
Related Issue: #1699
> feat: add js-entry-webpack-plugin to readme

- lib/child-compiler.js
fixes https://github.com/jantimon/html-webpack-plugin/pull/1847/
fixes https://github.com/jantimon/html-webpack-plugin/issues/1846
> fix: handle `childCompilation.errors` being an iterator rather than array
