jantimon/html-webpack-plugin

- index.js
Instruct webpack to watch and recompile when template file has changed.
Fixes #5
> Recompile if file has changed

- index.js
- spec/HtmlWebpackPluginSpec.js
This pull request allows to pass a synchronous function to generate the templateContent.
Might also fix #7
> Allow to pass a function for custom html rendering / templating

- package.json
- spec/HtmlWebpackPluginSpec.js
- spec/fixtures/main.css
- spec/fixtures/theme.js
This pull requests is based on #14 and #15.
The actual change is https://github.com/jantimon/html-webpack-plugin/commit/04e775da020f586ded526189b666fb2e0e3e0ee1
> Integration tests for extract-text-webpack-plugin

- package.json
> Use pretest

- index.js
- spec/HtmlWebpackPluginSpec.js
See ampedandwired/html-webpack-plugin/pull/45
> Change assets deprecation from error to warning

- README.md
- index.js
- spec/HtmlWebpackPluginSpec.js
Allows to inject javascript resources to the head instead of the body element
> Allow to inject javascript files into the head of the html page

- index.js
Addresses #56
cc @ampedandwired @jantimon
> Fix existing manifest regex test

- index.js
- spec/HtmlWebpackPluginSpec.js
- spec/fixtures/async.js
- spec/fixtures/index.js
> [async] make sure the async chunks aren't included in the html

- README.md
I copied the example, it gave me errors and it took me a moment to notice why.
> Fix example template

- index.js
This is a PR into the loaders PR
> Return minified html from promise

- README.md
- index.js
- spec/HtmlWebpackPluginSpec.js
I really want #41 merged, so I decided to fix one of the outstanding issues on it. I also merged it from master.
If there are more things I can do, please let me know.
> Fix a bug displaying errors and fix merge conflicts in PR #41 

- README.md
- index.js
I've added an example of how to use a loader template and merged master into feature/loaders.
> Add loader example in readme

- index.js
> Don't insert chunks that is not 'initial'

- package.json
3 tests failed without this dependency.
> Add jade dev dependency to fix tests

- lib/loader.js
Fixes issue https://github.com/ampedandwired/html-webpack-plugin/issues/213
> Accomodated for change to Loader API in Webpack 2

- migration.md
Maybe I should split this PR into 2 commits, you will tell me
* there was one comma `;` in the example that made my build crash.
* judging by the hard time people have when using this feature, including myself, there is clearly some miss-understanding #230 #202 #198 #176 
English is not my natural language, I might need some eyes on what I wrote though.
> Explicit documentation about sub-templating

- package.json
- spec/HtmlWebpackPluginSpec.js
- spec/support/jasmine.json
Focused specs make the upgrade worth it, IMO
> Upgrade jasmine to 2

- README.md
- index.js
- spec/HtmlWebpackPluginSpec.js
- spec/fixtures/custom_file.html
This allows you to add assets to the html when not using injection
> Add before-html-generation event

- package.json
- spec/BasicSpec.js
- spec/CachingSpec.js
- spec/ExampleSpec.js
Tests to ensure that the html is compiled only once (see #244)
> Add caching tests

- index.js
- spec/BasicSpec.js
> support absolute filenames

- CHANGELOG.md
- index.js
- lib/compiler.js
- package.json
- spec/BasicSpec.js
> Support hashes in filenames

- README.md
When I want to use `events` to alter htmls, the usage of `events` can't help me directly.
I spent much time on finding that what's the `compilation`. That's so sad.
> add demo code about events

- CHANGELOG.md
- lib/chunksorter.js
- package.json
- spec/BasicSpec.js
> Exclude chunks works now even if combined with dependency sort

- lib/compiler.js
ref #353 handle err before any logic in promise return by compileTemplate
> Handle err before any logic in promise return by compileTemplate

- index.js
- spec/BasicSpec.js
> Don't treat templateContent set to an empty string as not specified

- README.md
@jantimon 
I created a new pull request to keep the commits history simple.
> Update README.md with third party plugin html-webpack-exclude-assets-plugin

- README.md
Replacement for [PR 511](https://github.com/ampedandwired/html-webpack-plugin/pull/511)
Updated README
> Publicity for XXX-ext-html-webpack-plugins

- README.md
Added a description for `html-webpack-harddisk-plugin` and the new `preload-webpack-plugin` plugin from Google.
> Added new preload plugin and description update

- .github/issue_template.md
I stole it from there: https://github.com/avajs/ava/blob/master/.github/issue_template.md
I think it will be easier to take care of issues with this in place, most of the time I end asking the same question over and over
> chore(github): add issue_template.md

- index.js
- spec/BasicSpec.js
- spec/fixtures/spaced_plain.html
This PR aim to solve the issue:https://github.com/jantimon/html-webpack-plugin/issues/708
> Change headReg and bodyReg to allow spaces

- index.js
> fix(template): prevent undefined error in template loader

- CHANGELOG.md
Fixes some typos and adds missing links to issues and pull requests,
> Fix typos, add links to issues and pull

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
This should fix #798 where css entries where also added as a script tag.
> fix(entries): Don't add css entries twice

- README.md
Add html-webpack-exclude-empty-assets-plugin to the docs
> Add html-webpack-exclude-empty-assets-plugin

- examples/custom-template/readme.md
Change require html to require html-loader
> Updated readme.md to use "html-loader" instead of "html"

- .mailmap
In this way my past contribution is mapped correctly.
> Add a Git .mailmap with merged repeated occurrences of various people

- lib/loader.js
> fix(loader): Prevent foreign loaders from compile lodash

- README.md
- index.js
- spec/BasicSpec.js
> feat: Add meta tag option

- index.js
- spec/basic.spec.js
> feat: Add support for the [contenthash] placeholder inside htm file names

- index.js
- spec/basic.spec.js
- typings.d.ts
Allow to return a promise from the templateParameters option.  
Solves #1039
> feat: Allow to return async template parameters

- index.js
> Reject promises with errors

- README.md
add link to new html-webpack-link-type-plugin
> Add link to new html-webpack-link-type-plugin to README.md

- README.md
Update long-term caching details to the README.
Additionally, I corrected few typos.
> Add long-term caching details to README

- lib/errors.js
> Ignore pretty error errors

- lib/compiler.js
> Fixing No refresh on change in sub templates

- index.js
- spec/basic.spec.js
> fixed: relative publicPath

- README.md
Added package in readme for Issue - https://github.com/jantimon/html-webpack-plugin/issues/1158
This package solves these issues:
https://github.com/jantimon/html-webpack-plugin/issues/381, https://github.com/jantimon/html-webpack-plugin/issues/818, https://github.com/jantimon/html-webpack-plugin/issues/667, https://github.com/jantimon/html-webpack-plugin/issues/624, https://github.com/jantimon/html-webpack-plugin/issues/1158
> Add package in readme.md fixing issue issue #1158

- README.md
Created a new plugin to help limit executed file size.
> Added link and description for nomodule-plugin

- examples/README.md
Hello thank you for maintaining this project!
I created a sample for static landing page and also there are many good examples using this project.
But It's hard to find them.
So I made a README.md for "example".
How about it?
> docs: example README.md

- README.md
Fix miss typo.
```
Staic
```
```
Static
```
> Fix miss typo

- typings.d.ts
quick fix copied from [@types/html-webpack-plugin/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/html-webpack-plugin/index.d.ts)
for #1244
> fix(typings.d.ts): added apply method type to HtmlWwbpackPlugin class definition

- README.md
- examples/README.md
- examples/chunk-optimization/dist/webpack-4/entryA.js
- examples/custom-insertion-position/dist/webpack-4/bundle.js
- examples/custom-insertion-position/dist/webpack-4/index.html
- examples/custom-insertion-position/example.js
- examples/custom-insertion-position/index.ejs
- examples/custom-insertion-position/readme.md
- examples/custom-insertion-position/webpack.config.js
- examples/javascript/dist/webpack-4/index.html
- index.js
Added also examples who to set custom insertion points
> feat: add `.toString` implementation to htmlTags to allow easier render

- package.json
This pull request switches html-minifier to html-minfier-terser because of inactivity of https://github.com/kangax/html-minifier/issues/1040 for 3 month
> feat: Add support for minifying inline ES6 inside html templates

- examples/template-parameters/webpack.config.js
> docs: Update example for template parameters

- docs/template-option.md
> Fix typo in template option docs

- index.js
- spec/basic.spec.js
> feat: merge templateParameters with default template parameters

- index.js
this fixes a bug for hot module replacement:
https://github.com/webpack/webpack/issues/10790#issuecomment-620647237
thanks @sokra
> fix: prevent scripts marked as hotModuleReplacement from being added to the html file

- README.md
These paragraphs are identical
> docs: delete duplicate paragraph

- lib/html-tags.js
- typings.d.ts
- defaults added for TS consumption
- static `version` exposed
- static `createHtmlTagObject` exposed
- minor typos fixed
Thanks!
> docs: Type definition minor updates

- index.js
- lib/cached-child-compiler.js
- lib/child-compiler.js
- lib/file-watcher-api.js
- lib/html-tags.js
- spec/basic.spec.js
- spec/caching.spec.js
Noticed a few typos in comments and figured I'd submit a fix for them.
> fix: fix typos in comments

- package.json
I used the same range specification as [css-loader](https://github.com/webpack-contrib/css-loader/blob/master/package.json#L43)
> update webpack dependency range fix #1504

- README.md
[html-webpack-inline-source-plugin](https://github.com/DustinJackson/html-webpack-inline-source-plugin) is outdated
> Update Readme - no longer maintained plugin

- README.md
> Align section Minification with the code regarding `keepClosingSlash`

- README.md
Added this plugin made for html-webpack-plugin:
https://github.com/Jaid/inject-body-webpack-plugin
> Added inject-body-webpack-plugin to readme

- .github/workflows/main.yml
fixes https://github.com/jantimon/html-webpack-plugin/pull/1706
> ci: improve

- typings.d.ts
> fix(types): fix type for `chunkSortMode`

- spec/basic.spec.js
- spec/fixtures/templateParam.cjs
fixes https://github.com/jantimon/html-webpack-plugin/issues/1756
Already fixed in `5.5.2`, just a test case
> test: test case for the `cjs` extension

- index.js
- lib/cached-child-compiler.js
It potentially can break JSON streaming
> refactor: use logger to avoid pulling logs in output

- README.md
- spec/basic.spec.js
- typings.d.ts
Update docs and test to use getCompilationHooks
> docs: update
